color: pink
fieldLayouts:
  a0644623-0917-40f9-bc83-a5e5393de6f9:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: ea7263b0-142c-4c1f-89a0-89866c580aa7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d6a28be7-e265-4aa2-bfc0-5ea881151826 # Intro
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a11285b5-905e-49bb-898c-9594a6a5b342
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 53645872-6ce8-4f78-afde-3f9747ebee3a
        userCondition: null
handle: startpagina
hasTitleField: true
icon: house
name: Startpagina
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
