defaultPlacement: end
enableVersioning: true
entryTypes:
  - 0b8f983f-e608-4620-9a68-cef3874e06b3 # Startpagina
handle: home
maxAuthors: 1
name: startpagina
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  1de77200-750e-4009-a396-c2a04ff635a4: # my-craft-project
    enabledByDefault: true
    hasUrls: true
    template: home.twig
    uriFormat: __home__
type: single
